export const postItem = [
  {
    id: 'B9vUv0E0ibc0X55kVVLr',
    name: '홀란드',
    title: '포근한 니트로 만드는 나만의 글씨, 봉봉메이드 니트레터링 클래스',
    contents:
      '<h1>dasdasdas</h1>홀란드는 Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus nulla blanditiis, ducimus sed suscipit atque neque consequatur cum eveniet nostrum quisquam alias distinctio et beatae tempore temporibus ab non iste. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus nulla blanditiis, ducimus sed suscipit atque neque consequatur cum eveniet nostrum quisquam alias distinctio et beatae tempore temporibus ab non iste. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus nulla blanditiis, ducimus sed suscipit atque neque consequatur cum eveniet nostrum quisquam alias distinctio et beatae tempore temporibus ab non iste.',
    image: 'https://cdn.class101.net/images/3a25ecd9-d1ab-4d21-8cc1-522ea711e729',
    price: 560000,
    createDate: '2023.04.01',
    tags: ['tag3'],
    description: '포스트 소개입니당',
    series: '',
  },
  {
    id: '81x83ysiEHsHCBoeVh2O',
    name: '음바페',
    title: '글씨가 주는 소소한 행복, Lettering Together!',
    contents:
      '음바페은 Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus nulla blanditiis, ducimus sed suscipit atque neque consequatur cum eveniet nostrum quisquam alias distinctio et beatae tempore temporibus ab non iste.',
    image: 'https://cdn.class101.net/images/ec0f0c15-aeec-43a3-a0c9-b649b0999f0a',
    price: 654000,
    createDate: '2023.04.02',
    tags: ['tag3'],
    description: '포스트 소개입니당',
    series: '',
  },
  {
    id: 'gGFsFvhrKlvZpjLRfmNY',
    name: '메시',
    title: '붓펜으로 그려낸 보통날, 보통의 글씨',
    contents:
      '제임슨은 Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus nulla blanditiis, ducimus sed suscipit atque neque consequatur cum eveniet nostrum quisquam alias distinctio et beatae tempore temporibus ab non iste.',
    image: 'https://cdn.class101.net/images/a363a069-5aaf-40cb-822e-a2cab585c37e',
    price: 954000,
    tags: ['tag3'],
    createDate: '2023.04.03',
    description: '포스트 소개입니당',
    series: '',
  },
  {
    id: 'vgrdHO9bLqNxDYt4Q7vZ',
    name: '호날두',
    title: '수놓는 발바닥과 함께 하는 꽁냥꽁냥 고양이 자수',
    contents:
      '호날두은 Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus nulla blanditiis, ducimus sed suscipit atque neque consequatur cum eveniet nostrum quisquam alias distinctio et beatae tempore temporibus ab non iste.',
    image: 'https://cdn.class101.net/images/a363a069-5aaf-40cb-822e-a2cab585c37e',
    price: 123000,
    createDate: '2023.04.04',
    tags: ['tag3'],
    description: '포스트 소개입니당',
    series: '',
  },
  {
    id: 'CNCwXwHP7FUip83z5VEH',
    name: '네이마르',
    title: '소복소복 바늘 끝에서 피어오르는 자수',
    contents:
      '네이마르는 Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus nulla blanditiis, ducimus sed suscipit atque neque consequatur cum eveniet nostrum quisquam alias distinctio et beatae tempore temporibus ab non iste.',
    image: 'https://cdn.class101.net/images/38f79b22-4728-4c16-bee9-966fff07df3f',
    price: 456000,
    createDate: '2023.04.05',
    tags: ['tag3'],
    description: '포스트 소개입니당',
    series: '',
  },
  {
    id: 'ndHkNPUpGPiF4nmqX0PL',
    name: '페드리',
    title: '한 땀 한 땀 꽃을 수 놓다 - 보태니컬 입체 프랑스 자수',
    contents:
      '페드리는 Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus nulla blanditiis, ducimus sed suscipit atque neque consequatur cum eveniet nostrum quisquam alias distinctio et beatae tempore temporibus ab non iste.',
    image: 'https://cdn.class101.net/images/132a560b-ba7f-4564-b5f5-709b934f5ddd',
    price: 789000,
    createDate: '2023.04.06',
    tags: ['tag3'],
    description: '포스트 소개입니당',
    series: '',
  },
  {
    id: '4tVyp15jKUO6sfUvLnBc',
    name: '레반도프스키',
    title: '내가 그리고, 네가 간직할 인공의 아이패드 드로잉',
    contents:
      '레반도프스키는 Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus nulla blanditiis, ducimus sed suscipit atque neque consequatur cum eveniet nostrum quisquam alias distinctio et beatae tempore temporibus ab non iste.',
    image: 'https://cdn.class101.net/images/9e7be50d-72f1-4c93-80d6-c6b95b42bd40',
    price: 101000,
    createDate: '2023.04.07',
    tags: ['tag3'],
    description: '포스트 소개입니당',
    series: '',
  },
  {
    id: 'pHr0phFtcWhsgZhSVe9F',
    name: '손흥민',
    title: '글씨 쓰는 김이영과 함께 아이패드에 그려낸 캘리그라피',
    contents:
      '손흥민은 Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus nulla blanditiis, ducimus sed suscipit atque neque consequatur cum eveniet nostrum quisquam alias distinctio et beatae tempore temporibus ab non iste.',
    image: 'https://cdn.class101.net/images/864f377f-93d9-4520-94de-19ca142c432f',
    price: 359000,
    createDate: '2023.04.08',
    tags: ['tag3'],
    description: '포스트 소개입니당',
    series: '',
  },
]
